### ISSUE TITLE
File is not called "pong"

### ISSUE THREAD

**Issue by LordOfCheese1** [zlago/snek-gbc#2]
Man, quality standards nowadays. 0/20, wouldn't recommend whatsoever, it's not called "pong.gb" + the creator is absolutely terrible with grammar.

**Comment by LordOfCheese1** [comment]
Still not called "pong.gb" I'm dissapointed

**Comment by zlago** [comment]
so i internally just sort of went like "technically if i add a makefile with configurable output file name, i can close this", and now i sort of have a makefile (without any real config yet), so im considering this issue closed
